### ISSUE TITLE
publicPath set but does not do anything

### ISSUE THREAD

**Issue by Reidond** [ZachJW34/nx-plus#100]
## Current Behavior
publicPath set but does not do anything

## Expected Behavior
publicPath option to do something

## Steps to Reproduce
1. Set public path
```json
          "configurations": {
            "production": {
              "mode": "production",
              "filenameHashing": true,
              "productionSourceMap": true,
              "css": {
                "extract": true,
                "sourceMap": false
              },
              "publicPath": "./"
            },
            "development": {
              "mode": "development",
              "publicPath": "./"
            }
          }
```
2. Run with desired mode
3. index.html in dist do not have public path set

https://github.com/testing-student-app/stract2

### Environment

Plugin name and version: @nx-plus/vue@^10.0.0

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : 10.1.0
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.1.0
  typescript : 3.8.3

**Comment by ZachJW34** [comment]
The `publicPath` option works fine on my end. Here is an image of the generated `index.html` of an app built with no publicPath and publicPath=/my-app/.
![Screen Shot 2020-09-21 at 7 52 43 PM](https://user-images.githubusercontent.com/25158820/93835239-38d9e080-fc44-11ea-93db-99df2b378b22.png)
You are using a relative path so you can expect that the assets will not have a leading forward slash, but the behavior remains the same when serving a simple app. From what I tested, this behavior is in-line with the vue-cli so I'm going to close this issue.
https://cli.vuejs.org/config/#publicpath

**Comment by crutchcorn** [comment]
This works great!

However, and this could just be me, but I found the ability to overwrite Vue CLI config options from `workspaces.json` unclear until I found this issue. 

@ZachJW34, would you accept a PR to docs that adds mention to this functionality?

**Comment by ZachJW34** [comment]
@crutchcorn All of the builder options that we have documented [here](https://github.com/ZachJW34/nx-plus/tree/master/libs/vue#browser) can be specified inside the workspace.json or as command-line options. We could be more explicit with that connection in our documentation. That said, we would welcome a contribution if you think they can be improved!
