### ISSUE TITLE
How to add transpileDependencies in vue?

### ISSUE THREAD

**Issue by emjimadhu** [ZachJW34/nx-plus#104]
First of all i am really sorry for opening a new issue that is related to webpack config. This is related to vuetify.

## Description
A month pack i raised an issue about how to implement vuetify. You shared me a repo. That worked fine. Now i wanted to recreate it in a new project.

I created a new vue-cli project with vuetify. And i copy pasted all the files that vue-cli-plugin generated. One of the file it updated was vue.config.js to add `transpileDepencies` for vuetify. I dont know how to configure it in nx-plus/vue. Can you guide me please? 

Thank you. I am really sorry for this issue.

**Comment by ZachJW34** [comment]
No worries @emjimadhu! Do you need to add vuetify to `transpileDependencies` because you are having issues with IE11? If you don't need to support IE11 then I don't believe that option is necessary. The `transpileDependencies` option requires `babel` integration which we don't currently have (but is actively being worked on in #102).

**Comment by MatthieuLebigre** [comment]
Can't want to have this fixed :)

**Comment by MatthieuLebigre** [comment]
@ZachJW34 do you need help with the MR ? I see it hasn't be any activity for a while

**Comment by BuckyMaler** [comment]
@MatthieuLebigre Zach and I have been very busy at work lately, so we haven't had as much time to work on Nx Plus as we'd like. I'll review the PR soon.

**Comment by davidmoshal** [comment]
Hi wondering how best to add vuetify.   

First attempt was ` vue add vuetify ` in the app directory.  
However that failed due to   
`Error: The package.json file at <path omitted>/apps/vuetify/package.json' does not exist`

Suggestions on how to add vuetify would be much appreciated!

**Comment by davidmoshal** [comment]
Managed to get Vuetify to work.  
Instructions on how to add Vuetify to an existing project were helpful:
- https://vuetifyjs.com/en/getting-started/installation/#webpack-install

(1) Install Vuetify and sass loader:
```sh
npm install vuetify
npm install sass sass-loader deepmerge -D
```

(2) created a `src/plugins/vuetify.js` file
```js
import Vue from "vue";

// note: for some reason these options worked best:
import Vuetify from "vuetify";
import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify);

export default new Vuetify({}});
```

(3) create file `src/shims-vuetify.d.ts`:
```ts
import "vuetify/types";

declare module "vuetify/lib/framework" {
  import Vuetify from "vuetify";
  export default Vuetify;
}
```

(4) edit `main.ts`:
```ts
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import vuetify from "./plugins/vuetify";

Vue.config.productionTip = false;

new Vue({
  router,
  vuetify,
  render: (h) => h(App),
}).$mount("#app");
```

**Comment by MatthieuLebigre** [comment]
@ZachJW34 When do you plan to publish a release that includes this fix ?

**Comment by ZachJW34** [comment]
@MatthieuLebigre No later than this coming weekend!

**Comment by ZachJW34** [comment]
@MatthieuLebigre Version 10.4.0 was released with the `transpileDependencies` option. Check it out!
