### ISSUE TITLE
docusaurus - Generator is not using the workspaceLayout / appsDir for the generation

### ISSUE THREAD

**Issue by creadicted** [ZachJW34/nx-plus#105]
## Current Behavior
If I generate the app it will be generated in "apps/<name>/*" Even when the appsDir in the nx.json is set to a different folder. 

## Expected Behavior

That the generator uses the file path set in the nx.json file

```json
{ 
  "workspaceLayout": {
    "appsDir": "myAppsDir",
    "libsDir": "myLibsDir"
  }
}
```

**Comment by BuckyMaler** [comment]
@creadicted thanks for creating this issue. We've been aware of this, but haven't been able to get around to it. This would be a great contribution. Would you like to work on this?
