### ISSUE TITLE
@nx-plus/vue:app - Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by akolybelnikov** [ZachJW34/nx-plus#108]
## Current Behavior
The command `nx g @nx-plus/vue:app app_name` throws a console error: `Cannot read property 'toString' of null`, and no app is generated.

## Expected Behavior
The command should generate a Vue app in a freshly initialized NX workspace.

## Steps to Reproduce
`git clone https://github.com/akolybelnikov/go-vault-vue.git`, after that install dependencies with `yarn`, and try running the `nx g @nx-plus/vue:app app_name` in the terminal, in the root of the project.

### Failure Logs
No logs were generated.

### Environment
Plugin name and version: `@nx-plus/vue": "^10.0.0`

  nx : 10.2.1
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7

**Comment by akolybelnikov** [comment]
Update: the above described behavior is exhibited when I try to add the @nx-plus/vue:app in a workspace with an existing api project. If I start a new workspace from scratch with no preset chosen during the initialization, the plugin works correctly.

**Comment by ZachJW34** [comment]
@akolybelnikov Can you provide more info on what you mean by an existing api project? Is there an existing nrwl plugin that causes the `@nx-plus/vue` plugin to fail when installed together? A Github repo would be helpful.

**Comment by akolybelnikov** [comment]
@ZachJW34 yes, first I installed `https://github.com/nx-go/nx-go`. The link to the repo is above in the steps to reproduce.

**Comment by DavidDomkar** [comment]
Hello. I just created a new nx workspace and wanted to add nuxt app to it and I am facing the same error.

**Comment by ZachJW34** [comment]
Found the issue. It comes from providing the schematic a name with an underscore (in your example you provided `app_name`). Names are normalized in our schematic, so `app_name` would become `app-name`. This causes a problem when we invoke nx's cypress schematic which does not normalize the name. When we go to modify some of the files that the cypress schematic generated, we try to read files that don't exist (for example, `app_name-e2e/src/integration/app.spec.ts` vs `app-name-e2e/src/integration/app.spec.ts`).
@DavidDomkar @akolybelnikov Can you try generating an app without an underscore and see if your problem persists? I'll submit a fix for this issue regardless, but it can be a workaround until our next release is out.
