### ISSUE TITLE
App schematic fails with Nx v10.3.0

### ISSUE THREAD

**Issue by ZachJW34** [ZachJW34/nx-plus#109]
## Current Behavior
App schematic fails with Nx v10.3.0

## Expected Behavior
App schematic should work as expected.
## Steps to Reproduce
```
# Select empty preset
npx create-nx-workspace@latest my-repo && cd my-repo
yarn add -D @nx-plus/vue
nx g @nx-plus/vue:app my-app
```

### Failure Logs
<img width="563" alt="Screen Shot 2020-10-04 at 12 22 46 PM" src="https://user-images.githubusercontent.com/25158820/95022457-14ff9d00-063d-11eb-9dd2-1e6ee4adcf10.png">

### Environment
os: macOS 10.15.7 (19H2)
plugin: "@nx-plus/vue": "^10.0.0",

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3

**Comment by BuckyMaler** [comment]
This issue will be fixed as a part of the Nx update being done for #91. It's in progress.
