### ISSUE TITLE
"Cannot Read Property Unshift of Undefined"

### ISSUE THREAD

**Issue by valgaze** [ZachJW34/nx-plus#124]
## Current Behavior

- Existing NX workspace with 

- Install @nx-plus/vue [```npm install @nx-plus/vue --save-dev```]

- Generate vue application [```npx nx g @nx-plus/vue:app my-app```]

- Encounter an error about *"Cannot read property unshift of undefined"*

![image](https://user-images.githubusercontent.com/1396559/99348199-dcfb9480-284d-11eb-8162-122e884de116.png)

## Expected Behavior

- Add project to workspace and off to the races

## Steps to Reproduce

- I am unable produce a minimal reproducible repo of this existing workspace, I suspect there's a version/config/etc mismatch somewhere in an existing NX workspace

- After some snooping, I've confirmed the issue comes from this line: https://github.com/ZachJW34/nx-plus/blob/master/libs/vue/src/schematics/application/schematic.ts#L152-L155

```ts
    updateJsonInTree(`${options.projectRoot}/.eslintrc.json`, (json) => {
      json.extends.unshift(json.extends.pop());
      return json;
    }),
```

```updateJsonInTree``` comes from the @nrwl/workspace's tooling here: https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/ast-utils.ts#L496

* The json parameter is an empty object & json.extends errors out to  undefined

* Creating apps/my-app & adding an .eslintrc.json did not resolve the issue

**NOTE:** From a new, "fresh" workspace, the below works correctly: 

```sh
npx create-nx-workspace@latest
# cd my_project
npm install @nx-plus/vue --save-dev
npx nx g @nx-plus/vue:app my-app
npx nx serve my-app
```

### Failure Logs

* Cannot read property 'unshift' of undefined

### Environment

* Node: v10.15.3 

Plugin name and version: @nx-plus/vue:  ^10.2.0

  nx : Not Found
  @nrwl/angular : 10.2.0
  @nrwl/cli : 10.2.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.2.1
  @nrwl/nest : 10.2.1
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.2.0
  typescript : 3.9.7

**Comment by valgaze** [comment]
Update, might be a versioning issue?

This "fresh workspace" is pinned to 10.2.0 and fails

```
npx create-nx-workspace@10.2.0
# cd my_project
npm install @nx-plus/vue --save-dev
npx nx g @nx-plus/vue:app my-app
npx nx serve my-app
```

**Comment by BuckyMaler** [comment]
Sorry for the inconvenience. We need to update our docs describing version compatibility. Nx 10.3.0 introduced some fairly large changes to linting that we needed to adapt to. `@nx-plus/vue` >=10.1.0 is compatible with Nx >=10.3.0. `@nx-plus/vue` 10.0.0 is compatible with Nx <10.3.0.

I'm currently working on an issue related to dependencies and will include clarifying the details above in our docs. That being said, this is working as expected, so I'm going to close this issue.
