### ISSUE TITLE
Vue3.x Support Plan?

### ISSUE THREAD

**Issue by djkloop** [ZachJW34/nx-plus#128]
## Description

```shell
 # Does this plugin support vue3?
```
## Motivation

```shell
 # Vue3 has released the official version, are there any plans to support vue3?
```

**Comment by djkloop** [comment]
![image](https://user-images.githubusercontent.com/21050914/100964863-758b5780-3564-11eb-8c4f-7ca47c430fd9.png)

**Comment by BuckyMaler** [comment]
You've mentioned 2 or 3 different issues in this single issue. Vue 3 is supported using the `vueVersion` option. Support for project names with underscores was added [here](https://github.com/ZachJW34/nx-plus/pull/117) and will be included in our next release. Please open a separate issue for the Cypress error you mentioned and include steps to reproduce the error.
