### ISSUE TITLE
@nx-plus/vue:component command

### ISSUE THREAD

**Issue by djkloop** [ZachJW34/nx-plus#129]

**Comment by mehrad-rafigh** [comment]
@ZachJW34 @BuckyMaler I love your plugin guys and want to help
Can I grab this issue and create a draft PR?

**Comment by BuckyMaler** [comment]
@mehrad-rafigh thank you for your kind words and willingness to help. We'd appreciate your contribution.

Zach and I have discussed adding more schematics for Vue and we think that inspiration should be pulled from [Sarah Drasner's snippets](https://github.com/sdras/vue-vscode-snippets) because they're very popular. I'll compile a list of options this weekend and iron out expectations for a new component schematic. If you have suggestions for schematic options please share those.

**Comment by mehrad-rafigh** [comment]
We need to have `--project` just like @djkloop mentioned. 
`--style` should be supported too.

**Comment by BuckyMaler** [comment]
@mehrad-rafigh I think the following options should be supported:

| Options          | Description                                                                                                                                                       |
| ------------- | ---------------------------------------------------------------------------------------------------  |
| `--name`       | The name of your component.                                                                                                                       |
| `--project`    | The name of the project.                                                                                                                                 |
| `--directory` | A directory or nested directory where the component is placed, relative to the project's source root. |
| `--style`        | The extension to be used for styles.                                                                                                              |

Below is example output for a component with `--name hello-world` and default `--style css`:

```
<template>
  <p>Welcome to HelloWorld</p>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'HelloWorld',
});
</script>

<style scoped></style>
```

What do you think?

**Comment by mehrad-rafigh** [comment]
@BuckyMaler looks good to me. Which `style` extensions should be supported? The same when you create a new app?

**Comment by BuckyMaler** [comment]
Please support the following style extensions: `css`, `scss`, `stylus`, and `less`.

**Comment by mehrad-rafigh** [comment]
I'll start with the PR tonight and will have something push worthy by the end of this week.

**Comment by mehrad-rafigh** [comment]
What about a spec file @BuckyMaler?
