### ISSUE TITLE
Update to NX 11

### ISSUE THREAD

**Issue by mehrad-rafigh** [ZachJW34/nx-plus#135]
NX 11 has been released a while ago and seems to getting more stable.

**Comment by realityfilter** [comment]
Meanwhile is there a planned release date for 10.3.0.? There seems to be a lot of related commits already.

**Comment by ZachJW34** [comment]
@realityfilter we will have a new release soon.

**Comment by hloehrmann** [comment]
Hey, is this considered as done now that #157 was merged to `master`?

If so, when can we expect the new package to be released?

Thanks for your work!

**Comment by BuckyMaler** [comment]
> Hey, is this considered as done now that #157 was merged to master?

Yes!

> If so, when can we expect the new package to be released?

We'll release v11 by Monday.
