### ISSUE TITLE
how to configure webpack

### ISSUE THREAD

**Issue by davidmoshal** [ZachJW34/nx-plus#144]
Hi, firstly, thanks for a great library!

I've been struggling to add a simple configuration to webpack, specifically, to set `javascriptEnabled = true` as a less-loader configuration option, ie:
```js
{
        test: /\.less$/,
        use: [{
            loader: "style-loader"
        }, {
            loader: "css-loader"
        }, {
            loader: "less-loader",
            options: {
                javascriptEnabled: true
            }
        }]
}
```
However, the config object doesn't seem to follow the conventions in the Vue-cli link in this project's readme.  

Any suggestions on how to set the javascriptEnabled option on the less-loader would be appreciated.

Thanks

**Comment by ZachJW34** [comment]
Can you try this?
```
module.exports = (config) => {
  const lessRule = config.module.rules.find((rule) => rule.test.exec('.less'));
  for (const {use} of lessRule.oneOf) {
    const lessLoader = use.find(({ loader }) => loader.includes('less-loader'));
    lessLoader.options.javascriptEnabled = true;
  }
};
```
I logged the config object and started looking for anything less related.

**Comment by davidmoshal** [comment]
Seems to work, thank you! 
Separately, did you see my response to #104 with instructions on how to get Vuetify working?
You might want to put that in the docs somewhere, it's a bit buried in that issue.

**Comment by davidmoshal** [comment]
Following up on this: wondering how to add pluginOptions ?
The usual ways don't seem to work.
Thanks.

**Comment by ZachJW34** [comment]
Say you wanted to change the name of the index.html. That is an option of the `HtmlWebpackPlugin`, so I would do this:
```
module.exports = (config) => {
  const htmlWebpackPlugin = config.plugins.find(
    (plugin) => plugin.constructor.name === 'HtmlWebpackPlugin'
  );
  htmlWebpackPlugin.options.filename = 'custom.html';
};
```
