### ISSUE TITLE
      `You must specify vue-cli config options in '${workspaceFileName}'.`

### ISSUE THREAD

**Issue by davidmoshal** [ZachJW34/nx-plus#153]
## Current Behavior

If @nx-plus/vue finds a `vue.config.js` file then it throws the following Error, without any explanation or documentation:
```
      `You must specify vue-cli config options in workspace.json.
```

## Expected Behavior

Documentation will exist explaining how to set vue-cli config options in workspace.json.

## Steps to Reproduce

- add a vue.config.js file to a vue app
- run: nx serve <vue-app>

nx reports

  Node : 12.20.1
  OS   : linux x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by BuckyMaler** [comment]
I think the error message is clear. Options are documented [here](https://github.com/ZachJW34/nx-plus/tree/master/libs/vue#builders-ie-task-runners) and some are pre-configured when your app is generated.
