### ISSUE TITLE
[Vue] unable to create a new vue app into an empty workspace

### ISSUE THREAD

**Issue by billyjov** [ZachJW34/nx-plus#172]
## Current Behavior

![2021-04-25 22_10_43-Auswählen Windows PowerShell](https://user-images.githubusercontent.com/18737653/116008193-8facfb80-a613-11eb-9d89-98cec6127e14.png)

## Expected Behavior

```bash
nx g @nx-plus/vue:app vue-app
```

Should create a new app into the empty workspace. 

## Steps to Reproduce

- Create an empty workspace:  `npx create-nx-workspace` and choose empty
- Install plugin: `npm install @nx-plus/vue --save-dev`
- Generate app: `nx g @nx-plus/vue:app vue-app`

can be archieve with an empty workspace.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

![2021-04-25 22_10_43-Auswählen Windows PowerShell](https://user-images.githubusercontent.com/18737653/116008449-e6ff9b80-a614-11eb-850e-ba5691546c99.png)

### Environment

Plugin name and version: 

- OS: Windows 10
- Plugin Version: `^11.0.0``
- Terminal: Powershell, Git Bash,

```bash

>  NX  Report complete - copy this into the issue template

  Node : 12.16.1
  OS   : win32 x64
  npm  : 6.13.4

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

```

**Comment by BuckyMaler** [comment]
We don't officially support Nx v12 yet. I can't reproduce this error with v11.

I created an issue to add Nx v12 support to all plugins. #173

**Comment by LuckeeDev** [comment]
Same error here, should we just use v11 for now @BuckyMaler?

**Comment by BuckyMaler** [comment]
> Same error here, should we just use v11 for now @BuckyMaler?

@LuckeeDev yes. I'll add v12 support as soon as I can.
