### ISSUE TITLE
Vue app doesn't load in nx-electron

### ISSUE THREAD

**Issue by JensVanhulst** [ZachJW34/nx-plus#179]
## Current Behavior
I tried to add electron support to my Vue app generated with ```nx g @nx-plus/vue:app my-app``` and electron with : ```nx g nx-electron:app <electron-app-name> **--frontendProject=<frontend-app-name> ``` . 

When starting up the vue app, everything works fine. But when I try to launch with electron using ``` nx run-many --target=serve --projects=<frontend-app-name>,<electron-app-name> --parallel```. It loads without an HTML file.  

![image](https://user-images.githubusercontent.com/43351822/122561804-93249800-d042-11eb-925f-03ca4e69eae0.png)

According to the code I find in my app.ts (from electron) . I can see that it is looking in the dist directory 
```ts
App.mainWindow.loadURL(
   format({
      // file:///C:/Users/my-user/my-workspace/dist/packages/app/public/index.html
      pathname: join(__dirname, '..', rendererAppName, 'index.html'),
      protocol: 'file:',
      slashes: true,
    })
  );
```
But when the vue app is served it does not output it's build files to the dist folder. Resulting in a not found HTML file. 
But even if I manually change the path to use the html file in my generated app 
`file:///C:/Users/jensv/my-workspace/packages/app/public/index.html`, it still shows a blank html file.

I also configured the vue router to use 'hash' mode in electron.

## Steps to Reproduce
1. create an nx workspace with : `npx create-nx-workspace@latest my-workspace`
2. Generate a VUE app : `nx g @nx-plus/vue:app app`
3. Create electron app based on vue app : `nx g nx-electron:app desktop --frontendProject=client`
4. Run the project with : `nx run-many --target=serve --projects=app,desktop --parallel`

GitHub repo : https://github.com/JensVanhulst/nx-vue-bug/tree/main/packages

More info about nx-electron : https://github.com/bennymeg/nx-electron

### Failure Logs
none 

### Environment

Plugin name and version: 
my-workspace@0.0.0 C:\Users\my-suer\my-workspace
`-- nx-electron@11.1.2
`-- @nx-plus/vue@12.0.0

>  NX  Report complete - copy this into the issue template
  Node : 14.17.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.4.0
  @nrwl/cypress : 12.0.0
  @nrwl/devkit : 12.4.0
  @nrwl/eslint-plugin-nx : 12.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.0
  @nrwl/linter : 12.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.4.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by BuckyMaler** [comment]
We'd like to support Electron, but it's not a high priority of ours. Please consider contributing a fix. May be @bennymeg can provide some direction.

**Comment by bennymeg** [comment]
Firstly, make sure you are either using port 4200 or updating app.ts to use the correct port.
Another thing that might happen is that the electron app finished compiling before your vue app (which is most likely to happen) to fix that you can either serve you app in two stages, or using the hot reload feature to update the app.

**Comment by BuckyMaler** [comment]
@JensVanhulst have you been able to try what @bennymeg suggested?

**Comment by JensVanhulst** [comment]
@bennymeg @BuckyMaler. I have been busy lately. But today I gave it another shot.
 It appeared to be the rendererAppPort was set to 4200 (as mentioned). After changing this to 8080 the app launched. 
 I overlooked the port number in the config (my bad). 
 
 Thanks for helping !
