### ISSUE TITLE
Docusaurus builder Imcompatible with Terser 5+

### ISSUE THREAD

**Issue by Nightbr** [ZachJW34/nx-plus#181]
Hey,
hope you're doing well!

I have an issue with `@nx-plus/docusaurus` to build the docs in prod.

Context: https://github.com/facebook/docusaurus/issues/3515#issuecomment-851504933

## Current Behavior

Environment:

-  Monorepo manage by Nx 12.4
-  @nx-plus/docusaurus Nx plugin 12.0.0
-  Yarn
-  Docusaurus 2.0.0-beta.1
-  webpack 5+

When building with Docusaurus, I run into the known issue about monorepo & Terser, documented in your [Readme](https://github.com/ZachJW34/nx-plus/tree/master/libs/docusaurus#troubleshooting).

But If I set terser to 4.8

```
  "resolutions": {
    "terser": "4.8.0"
  }
```

I cannot build my other apps in my monorepo:

```
$ nx build api

> nx run api:build 
Starting type checking service...
Using 4 workers with 1024MB memory limit
Cannot read property 'tap' of undefined

———————————————————————————————————————————————

>  NX   ERROR  Running target "api:build" failed

  Failed tasks:
  
  - api:build
```

I don't know exactly if it's an issue directly with Docusaurus or @nx-plus/docusaurus or Terser itself.

There is this issue on Docusaurus about this: https://github.com/facebook/docusaurus/issues/3515

Work without issue with `Docusaurus 2.0.0-alpha.71`.

Perhaps it's an issue only related to Docusaurus, so it need to be tackled by Docusaurus. But if someone as insight here it could be great to discuss.

## Expected Behavior

Be able to build any apps using the same version of Terser.

## Steps to Reproduce

1. Nx 12.4 monorepo
2. Install @nx-plus/docusaurus
3. upgrade to @docusaurus 2.0.0-beta.1
4. Add another app (nestjs)

If you try to build the docs `nx build docs` you will have the error:

```
Docusaurus user: you probably have this known error due to using a monorepo/workspace.
We have a workaround for you, check https://github.com/facebook/docusaurus/issues/3515
```

If you add the workaround in package.json:

```
  "resolutions": {
    "terser": "4.8.0"
  }
```

Another app will failed building:

```
$ nx build api

> nx run api:build 
Starting type checking service...
Using 4 workers with 1024MB memory limit
Cannot read property 'tap' of undefined

———————————————————————————————————————————————

>  NX   ERROR  Running target "api:build" failed

  Failed tasks:
  
  - api:build
```

### Environment

-  Monorepo manage by Nx 12.4
-  @nx-plus/docusaurus Nx plugin 12.0.0
-  Yarn
-  Docusaurus 2.0.0-beta.1
-  webpack 5+

Thanks for any help!

**Comment by Nightbr** [comment]
Upgrading to `Nx 12.6`, `webpack 5` & `docusaurus-2.0.0-beta.3` fixed the issue \o/

```
$ nx build docs

> nx run docs:build 

[en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 8.86s


✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

Success! Generated static files in "dist/apps/docs".

Use `npm run serve` command to test your build locally.


———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build" succeeded
```

- https://blog.nrwl.io/next-js-11-webpack-5-for-web-node-streamlined-jest-config-and-more-in-nx-12-6-f8cd5be4fb
- https://nx.dev/latest/react/guides/webpack-5

**Comment by TomasFuentes** [comment]
Hello!. I'm facing the same problem, But I tried with the solution mentioned by @Nightbr and it hasn't worked for me, the addition of the docusaurus app breaks the build of my other apps. Could you share with me your package json?
