### ISSUE TITLE
[Vue] TypeScript inferred prop types fail build

### ISSUE THREAD

**Issue by crutchcorn** [ZachJW34/nx-plus#187]
## Current Behavior

It seems, that if you use a typed property in a TypeScript Vue component:

```typescript
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'NotifCardBase',
  props: {
    soundUrl: {
      type: String
    },
  },
  setup(props) {
    function test(val: string) {return val};

    test(props.soundUrl);
  }
})
```

It will throw an error

## Expected Behavior

This should not throw an error. In the minimal reproduction I provided (see below), I confirmed that the exact same Vue component does now throw an error and both serves and builds perfectly fine.

This issue also only occurs on `vue@>=3.0.8`. When using `vue@3.0.7`, there are no problems.

I believe this may be due to a change made upstream. When looking at [the changelog of `3.0.8`](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#308-2021-03-26), the only change that relates to TypeScript originates from this PR:

https://github.com/vuejs/vue-next/pull/3119

This PR also changes types directly associated with props, which increases my suspicion.

## Steps to Reproduce

https://github.com/oceanbit/nx-plus-vue-ts-infer-bug (includes instructions and both `vue-cli` [with no problems] as well as freshly `nx` generated project [with error])

### Failure Logs

```
  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.127:8080/

  Note that the development build is not optimized.
  To create a production build, run nx build my-app --prod.

ERROR in apps/my-app/src/NotifCardBase.vue:31:12
TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.
    29 |       function test(val: string) {return val};
    30 |
  > 31 |       test(props.soundUrl);
       |            ^^^^^^^^^^^^^^
    32 |     }, {
    33 |       immediate: true
    34 |     });

Terminate batch job (Y/N)? Y
```

### Environment

Plugin name and version: 

```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.3
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.0
  @nrwl/cypress : 12.0.0
  @nrwl/devkit : 12.0.0
  @nrwl/eslint-plugin-nx : 12.0.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.0
  @nrwl/linter : 12.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.6
```

**Comment by BuckyMaler** [comment]
Thanks for reporting this and great details!

I discovered while playing around in your repro that setting `"strict": true` in the `my-app` project's local `tsconfig.json` fixed the issue. I think that should be our default because of this, #185, and it's the default in Vue CLI.

Would you like to contribute the fix? You'd need to make the change for the app and library schematics.

**Comment by crutchcorn** [comment]
Oh! Awesome!

I actually would love to make this contribution!

Is this also something that we could update with a `nx upgrade` schematic as well? Hopefully that way other consumers won't run into similar issues

**Comment by BuckyMaler** [comment]
Thanks!

I don't think a migration schematic should be paired with this because it can result in many other errors that would break builds. I imagine user frustrations similar to [this](https://github.com/ZachJW34/nx-plus/issues/185#issuecomment-881226300).
