### ISSUE TITLE
Nuxt compilation error - Cannot find module '@babel/preset-env/lib/utils'

### ISSUE THREAD

**Issue by BuckyMaler** [ZachJW34/nx-plus#190]
## Current Behavior

A compilation error for a newly generated Nuxt app.

## Expected Behavior

No compilation errors for a newly generated Nuxt app.

## Steps to Reproduce

1. `npx create-nx-workspace@^12.0.0`
2. `cd my-workspace`
3. `npm install @nrwl/cypress@^12.0.0 @nrwl/jest@^12.0.0 @nrwl/linter@^12.0.0 --save-dev`
4. `npm install @nx-plus/nuxt --save-dev`
5. `nx g @nx-plus/nuxt:app my-app`
6. `nx serve my-app`

### Failure Logs

![Screen Shot 2021-07-24 at 2 30 32 PM](https://user-images.githubusercontent.com/14145352/126879415-fb61e58a-6e52-426e-a5ac-0385122ad941.png)

### Environment

Plugin name and version: `@nx-plus/nuxt@12.0.0`

Node : 14.15.1
OS   : darwin x64
npm  : 6.14.8

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.6.2
@nrwl/cypress : 12.6.2
@nrwl/devkit : 12.6.2
@nrwl/eslint-plugin-nx : 12.6.2
@nrwl/express : Not Found
@nrwl/jest : 12.6.2
@nrwl/linter : 12.6.2
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 12.6.2
@nrwl/web : Not Found
@nrwl/workspace : 12.6.2
@nrwl/storybook : Not Found
@nrwl/gatsby : Not Found
typescript : 4.3.5

**Comment by BuckyMaler** [comment]
Workaround: https://github.com/nuxt/nuxt.js/issues/8882#issuecomment-784031978

**Comment by nathandaly** [comment]
@BuckyMaler I added `"pre-install": "npx npm-force-resolutions"` to main the nx `package.json` file and still faces the same output. I use NPM, have I missed something?

```
Node : 14.17.3
  OS   : darwin x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.2
  @nrwl/cypress : 12.6.2
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : 12.6.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by nathandaly** [comment]
Ah I needed the below also even though I thought that was just for yarn users.

```
 "resolutions": {
    "@babel/preset-env": "~7.12.17"
  }
```

**Comment by nidomiro** [comment]
I had the same problem after a clean setup (Readme followed) today. Upgrading the `nuxt` dependency to `^2.15.8` fixed the issue for me

**Comment by oben01** [comment]
Any update on this issue ?
