### ISSUE TITLE
Help with ESLint on save and Code Coverage %

### ISSUE THREAD

**Issue by TASimpson** [ZachJW34/nx-plus#196]
This is my first time starting a discussion so I hope this is right :)

But I have followed the steps from https://www.npmjs.com/package/@nx-plus/vue to create my vue app. So far it has been great! I have downloaded NX Console and all commands listed from serving up the app to running simple commands has been easy to follow. I am only left with a couple of issues that my team would like me to do for our "sample app". 

1 - Have Lint run on save -- rather than always having to run `nx lint` 
2 - Have the tests run for that project and show code coverage on save -- rather than always having to run `nx test` 

Can these be done and how can I achieve them? I have been trying to use my google skills to find the answer, however, no luck.

**Comment by ZachJW34** [comment]
We explicitly disabled linting on save because running `nx lint` is the _Nx_ way to handle linting, same with `nx test`. That might feel strange coming from, say, a Vue CLI project where you might have had linting and testing on save but the separate commands fits into the Nx ecosystem better.
