### ISSUE TITLE
What is involved in boosting the version of NX in nx-plus.

### ISSUE THREAD

**Issue by idrise** [ZachJW34/nx-plus#204]
## Description
What is involved in boosting the version of NX in nx-plus.

**Comment by ZachJW34** [comment]
Mostly migrating the repo itself and making sure the builders/schematics still work. We sometimes write our own migrations but they can be a bit of a hassle. I've been away from contributing to this repo for a bit but I plan on getting them all up to date soon

**Comment by ZachJW34** [comment]
Support for v13 has been added.
