### ISSUE TITLE
How to enable runtimeCompiler

### ISSUE THREAD

**Issue by SimonDever** [ZachJW34/nx-plus#224]
## Description

With Vue3, is there a way to turn on `runtimeCompiler`? I tried the [existing PR](https://github.com/ZachJW34/nx-plus/pull/164) that allows the `vue.config.js` file to be used as per [this request](https://github.com/ZachJW34/nx-plus/issues/160) but still couldn't seem to define the `runtimeCompiler` no matter how I tried. I want to configure custom elements during runtime using `app.config.compilerOptions.isCustomElement` but `nx-plus/vue` already has `vue-loader` configured so I can't change the options and add `isCustomElement` in `configure-webpack.js`. My custom elements are not in `.vue` files, they're defined in `.ts` files but the tags are used in the HTML of `.vue` files but they are continually loaded by Vue and show the warning despite my best efforts to have them ignored.

**Comment by ZachJW34** [comment]
You can see what vue-cli does when you pass [runtimeCompiler](https://github.com/vuejs/vue-cli/blob/926855fac7a52ea960c00720f09196cd13b443ff/packages/%40vue/cli-service/lib/config/base.js#L70). Can you try setting the proper alias inside `configure-webpack.js` and see if that works?

**Comment by RFreij** [comment]
I had to add this to configure-webpack.js to enable runtimeCompiler:

```
module.exports = (config) => {
  config.resolve.alias = {
    'vue$': 'vue/dist/vue.esm.js'
  }
};
```

I don't (yet?) know about the compilerOptions.isCustomElement though..

**Comment by SimonDever** [comment]
Beautiful, that works perfectly to turn it on, thank you. I'll keep plugging away at configuring `compilerOptions` to register the custom elements and prevent the warning. Will make a new issue if required.
