### ISSUE TITLE
ERROR  Invalid options in inline options: "css.requireModuleExtension" is not allowed

### ISSUE THREAD

**Issue by dpietrzyk** [ZachJW34/nx-plus#225]
## Current Behavior

Error during build vue app.

![image](https://user-images.githubusercontent.com/32246156/155861530-c7cd80c0-de09-41cd-93c6-712e03da100e.png)

`ERROR  Invalid options in inline options: "css.requireModuleExtension" is not allowed` after upgrade `@vue/cli-service` from `4.5.15` to `5.0.1`

From v5 version this option is removed from CLI: https://cli.vuejs.org/config/#css-requiremoduleextensionv

## Expected Behavior

Build without any error.

## Steps to Reproduce

1. Generate project with vue app
2. Update `@vue/cli-service` to lastest 4.* version e.g. "4.5.15"
3. Build app `nx build app` -- _success_
4. Update `@vue/cli-service` to 5.* version e.g. "5.0.1"
5. Build app `nx build app` and observe error `ERROR  Invalid options in inline options: "css.requireModuleExtension" is not allowed` 

### Failure Logs

`ERROR  Invalid options in inline options: "css.requireModuleExtension" is not allowed` 

### Environment

Plugin name and version: 

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : linux x64
   npm  : 8.3.0
   
   nx : 13.8.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nx-plus/vue: 12.2.0
         @simondotm/nx-firebase: 0.3.3

**Comment by ZachJW34** [comment]
We don't support vue-cli@5 yet. Might be easy to add, might be hard but this would be a feature request.

I've opened https://github.com/ZachJW34/nx-plus/issues/228 to track vue-cli-5 support.
