### ISSUE TITLE
Support for Nx v14?

### ISSUE THREAD

**Issue by gregveres** [ZachJW34/nx-plus#241]
## Description
Are there plans to support Nx v14? 
I just found out that jest doesn't work under Nx v13 but if I use Nx v14 instead, then running jest works just fine. 

## Motivation
I am trying to migrate my Vue 2 application into Nx. I have over 6000 jest based unit tests and now that I have the app building in Nx, I turned my attention to the unit tests only to find that Nx crashes when I try to run the unit test on a freshly created TS library. I have filed a bug with Nx about this, but I doubt they will address it since it works fine in Nx v14. I did the exact same setup in v14 and it worked fine. 

The only think holding me back from moving to nx v14 is Nx-plus/vue

## Suggested Implementation
Unfortunately I have no idea what it would take to move to Nx v14, but from the issues I read here, it seems that it surrounds the patching of the dependency graph that is the stumbling block

Could you comment on a time frame or the likelihood of moving up to v14?

**Comment by ZachJW34** [comment]
v14 landed so check it out!
