### ISSUE TITLE
Add NX 14.3.X Support

### ISSUE THREAD

**Issue by sforner405** [ZachJW34/nx-plus#262]
## Description
Currently build is not possible with NX 14.3.6

<img width="369" alt="image" src="https://user-images.githubusercontent.com/29813520/176451275-f1cdbcae-11f2-4254-a77f-ba24caced095.png">

## Motivation
Be able to use latest NX version

**Comment by ZachJW34** [comment]
Working on a PR here: https://github.com/ZachJW34/nx-plus/pull/263

**Comment by ZachJW34** [comment]
https://github.com/ZachJW34/nx-plus/releases/tag/v14.1.0 has been published, check it out!

**Comment by sforner405** [comment]
Works! Thanks @ZachJW34 !
