### ISSUE TITLE
Add support for Nx 10

### ISSUE THREAD

**Issue by jonhermansen** [ZachJW34/nx-plus#43]
I ran into some problems adding/running a vue app in my monorepo that was generated with create-nx-workspace@10.0.0-beta.0

Steps to reproduce:
```
npm -g install create-nx-workspace@next @nrwl/cli@next
create-nx-workspace # Angular + Nest, no routing, no CSS preprocessing
cd my-project-name
npm install --save-dev @nx-plus/vue
# fix up postinstall script by hand, so that we can re-run npm install and trigger it
npm install
nx g @nx-plus/vue:app ui-vue
nx serve ui-vue
```

I do not have the error message on hand but can add this info later. There is an issue with CopyWebpackPlugin config transformation that is happening here: https://github.com/ZachJW34/nx-plus/blob/master/libs/vue/src/webpack.ts#L103

**Comment by ZachJW34** [comment]
@jonhermansen Thanks for checking out the package! I've opened a [PR](https://github.com/ZachJW34/nx-plus/pull/44) that should resolve this issue.

**Comment by jonhermansen** [comment]
Hey Zachary, thank you for the excellent work on the project!

I tried building your PR branch locally and installed into my monorepo, here is the error I get:

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                                                                                                                           11:44:47 PM

 error  in /home/jon/foo/apps/vue-app/tsconfig.app.json

[tsl] ERROR
      TS5083: Cannot read file '/home/jon/foo/tsconfig.json'.

 @ multi ./node_modules/@vue/cli-service/node_modules/webpack-dev-server/client?http://172.31.147.10:4200/sockjs-node (webpack)/hot/dev-server.js ./apps/vue-app/src/main.ts

 error  in ./apps/vue-app/src/main.ts

Module build failed (from /home/jon/foo/node_modules/@vue/cli-plugin-typescript/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (/home/jon/foo/node_modules/@vue/cli-plugin-typescript/node_modules/ts-loader/dist/index.js:19:18)

 @ multi ./node_modules/@vue/cli-service/node_modules/webpack-dev-server/client?http://172.31.147.10:4200/sockjs-node (webpack)/hot/dev-server.js ./apps/vue-app/src/main.ts

Type checking in progress...
No type errors found
Version: typescript 3.9.6
Time: 1888ms
```

I think this issue has to do with tsconfig.json in the root of nx workspace being renamed to tsconfig.base.json. If I fix this reference by hand in the generated vue app, it launches just fine!

By the way, I got vue to work on my end by using the stable version of create-nx-workspace. I just thought to make this bug in advance of whenever nx goes to version 10. Thanks again.

**Comment by jonhermansen** [comment]
About the removal of tsconfig.json, switch to tsconfig.base.json in nx 10: https://github.com/nrwl/nx/issues/3251#issuecomment-655561822
