### ISSUE TITLE
Public Path option

### ISSUE THREAD

**Issue by myin142** [ZachJW34/nx-plus#50]
Would it be possible to add the public path option from vue directly to this plugin? I do not think there is another way to set this. When using the `vue.config.js` it will disable all the other options set in `workspace.json`.

**Comment by BuckyMaler** [comment]
Absolutely! I'd ask if you're interested in working on this, but I'm actually already working on it. My work will make a number of `vue.config.js` options available in `workspace.json`. I think it'll be included in our next release, which will probably be this coming weekend.
