### ISSUE TITLE
How to add webpack.config.js for Vue plugin?

### ISSUE THREAD

**Issue by emjimadhu** [ZachJW34/nx-plus#90]
## Description
I am trying to integrate `Vuetify` in my vue app. So i have to follow the webpack integration to make it work from the documention.

https://vuetifyjs.com/en/getting-started/quick-start/#webpack-install

i want to put some default webpack config in wwebpack.config.js file. So how can i add it?

**Comment by ZachJW34** [comment]
I was able to integrate vuetify without having to manipulate the webpack config. Check out this repo [demoing vuetify](https://github.com/ZachJW34/nx-plus-vuetify). I followed the documentation for installing vuetify in a vue-cli powered project and copied the changes over.

**Comment by emjimadhu** [comment]
Thank you so much it worked perfectly. I just have few things i observed.

1. For some reasons, my onsave lint in vscode is not working at all. It is working for other apps. But not for vue.
2. The test files does not detect jest env in vscode but it is working on other apps too.
3. It seems like the `environment.ts` is not avaiable. When i try to create one manually and add "fileReplacements" key in workspace. It is giving me a error saying that i cant use that key. Is there a plan to support it?

Thanks.

**Comment by ZachJW34** [comment]
Glad I could help!
1. I'm not too familiar with eslint onsave, but I downloaded the eslint extension, added `"editor.codeActionsOnSave": { "source.fixAll.eslint": true }` and it was working correctly. This was done with a fresh nx workspace mind you.
2. Could you create an issue regarding this with some more details? I can take a look but I'd need some more information.
3. We considered supporting fileReplacements but opted to stick with supporting what the vue-cli supports when it comes to [environment variables](https://cli.vuejs.org/guide/mode-and-env.html#example-staging-mode).
