### ISSUE TITLE
Vue files aren't being linted

### ISSUE THREAD

**Issue by BuckyMaler** [ZachJW34/nx-plus#91]
## Current Behavior

Vue files aren't being linted.

## Expected Behavior

Vue files are linted.

## Steps to Reproduce

1. `yarn create-playground`
2. `nx g @nx-plus/vue:app my-app`
3. Add a lint error to a `.vue` file
4. `nx lint my-app`

### Environment

Plugin name and version: `@nx-plus/vue@0.5.0` 

```
@nrwl/angular : Not Found
@nrwl/cli : 9.4.5
@nrwl/cypress : 9.6.0
@nrwl/eslint-plugin-nx : 9.4.5
@nrwl/express : Not Found
@nrwl/jest : 9.6.0
@nrwl/linter : 9.6.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 9.4.5
@nrwl/web : Not Found
@nrwl/workspace : 9.4.5
typescript : 3.8.3
```

In the image below there's a debugger statement in `main.ts` and `App.vue`, but the lint error is only caught in `main.ts`.

![Screen Shot 2020-08-20 at 10 46 11 PM](https://user-images.githubusercontent.com/14145352/90850803-5e6b8580-e338-11ea-8506-68d3415867aa.png)

**Comment by BuckyMaler** [comment]
@rarmatei I see you did quite a bit of work on `@nrwl/linter`. I don't think this issue belongs in Nx because it doesn't support Vue internally, but I was hoping you could provide some direction.

**Comment by rarmatei** [comment]
@BuckyMaler sorry for the late response - I'm wondering if it's missing a plugin?

if you create an Nx workspace with a React app, you'll notice `"plugins": ["@typescript-eslint", "@nrwl/nx"],` in the root `.eslintrc` - which allows it to lint `.ts` files.

I've not worked with Vue before, but could it be that you need something like https://eslint.vuejs.org/ in there?

**Comment by rarmatei** [comment]
Can you try adding this to your local `.eslintrc.js` file:

```js
  "parser": "vue-eslint-parser",
  "parserOptions": {
    "parser": "@typescript-eslint/parser",
    "project": null
  },
  // ........
```

We use the `project` option to give "type information context" to the `@typescript-eslint/parser` - but for some reason that is not working with the `vue-eslint-parser` parser. They do tell you in their docs that you can use a custom parser, but it might be a question for them as to why you can't pass in the `project` option as well.

The above should work fine. The only cases where it won't work, is if somebody needs to use a rule that needs type info like the ones in:

`"plugin:@typescript-eslint/recommended-requiring-type-checking"`

**Comment by BuckyMaler** [comment]
@rarmatei thanks for responding. Unfortunately, adding that snippet to the local `.eslintrc.js` didn't work.

I think the linter builder is excluding `.vue` files. As you can see in the screenshot below I logged the files to lint and no `.vue` files were logged.

<img width="1680" alt="Screen Shot 2020-09-04 at 7 08 46 PM" src="https://user-images.githubusercontent.com/14145352/92292595-9f8c9980-eee3-11ea-8156-d47c13cf91da.png">

I also added the following npm script with no ESLint config changes and `App.vue` was linted.

```
"eslint": "eslint --config apps/my-app/.eslintrc.js --ext .js,.ts,.vue apps/my-app/src"
```

<img width="887" alt="Screen Shot 2020-09-04 at 6 31 40 PM" src="https://user-images.githubusercontent.com/14145352/92292622-d06cce80-eee3-11ea-8ead-5913946f649d.png">

I think the issue maybe the arguments passed to `ts.parseJsonConfigFileContent` or `ts.createProgram` found [here](https://github.com/nrwl/nx/blob/3461a86c6df9c2320f827fc70f2af383f9bae033/packages/linter/src/builders/lint/utility/ts-utils.ts#L40).

**Comment by rarmatei** [comment]
Oh, I was using Nx 10 when trying the example above! 

Can you show me what options you're sending to the linter, please? Or if you have an example repo that would help too, please.

There's been a recent change to what pattern we use for the "exclude" array.

**Comment by BuckyMaler** [comment]
I've narrowed in on the issue. [`parseJsonConfigFileContent`](https://github.com/nrwl/nx/blob/3461a86c6df9c2320f827fc70f2af383f9bae033/packages/linter/src/builders/lint/utility/ts-utils.ts#L60) excludes `.vue` files by default. However, it accepts an `extraFileExtensions` argument. Replacing that line with following gets us half way there:

```
const parsed = ts.parseJsonConfigFileContent(
  config.config,
  parseConfigHost,
  path.resolve(projectDirectory),
  { noEmit: true },
  undefined,
  undefined,
  [{ extension: '.vue', isMixedContent: true, scriptKind: 7 }]
);
```

[`createProgram`](https://github.com/nrwl/nx/blob/3461a86c6df9c2320f827fc70f2af383f9bae033/packages/linter/src/builders/lint/utility/ts-utils.ts#L82) also exlcudes `.vue` file by default. Unfortunately, it doesn't accept an `extraFileExtensions` argument. However, if you set `allowNonTsExtensions` to `true` before calling it, then `.vue` files will be included. To do that add the following right after the line above:

```
parsed.options.allowNonTsExtensions = true;
```

With those two changes `.vue` files are linted. I can see the first change being a PR into Nx, but not the second. `allowNonTsExtensions` is a private/internal TS option. [Here](allowNonTsExtensions) is where `createProgram` filters out `.vue` files if `allowNonTsExtensions` is not `true`.

Because of how `createProgram` works, I think we'll need to write our own linter builder, but [here](https://github.com/BuckyMaler/nx-lint-repro) is a repo to easily reproduce the issue if you want to take a closer look. After cloning the repo and installing deps, run `nx lint my-app`. There should be lint errors in `main.ts` and `App.vue`, but only the lint errors in `main.ts` are reported.

**Comment by rarmatei** [comment]
Interesting, thank you for that analysis!! I was using the Webstorm/VsCode linting warnings when I made those comments above, and forgot to actually try out invoking the Nx linter above 🤦 

If you explicitly set the files you want linted in the builder, it should start picking them up:

```json
"lint": {
          "builder": "@nrwl/linter:lint",
          "options": {
            "linter": "eslint",
            "files": ["**/*.{ts,vue}"],
            "exclude": ["**/node_modules/**", "!apps/my-app/**/*"]
          }
},
```

I tried using a few rules which require type information and it continues to work fine and pick them up. The downside I guess is that it includes all files in the glob, rather than only the ones you use in your `tsconfig` dependency graph.

I did notice that the `@angular-eslint/builder` (after which our builder is based off) has removed any references to `createProgram` etc., and I think is using the `eslint` config overrides to specify `tsconfigs`:

https://github.com/angular-eslint/angular-eslint/blob/master/packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js#L41

We do plan on updating our Nx linter to reflect some of the awesome updates made by James Henry above - but in the meantime, I don't know if you want to try using the above builder directly? (if the `files` option doesn't work for you)

**Comment by BuckyMaler** [comment]
It seems we have a couple of options to think through. @rarmatei thanks for your help on this! 😄

**Comment by rarmatei** [comment]
> It seems we have a couple of options to think through. @rarmatei thanks for your help on this! 😄 

Cool!! Excited to see this plugin grow! Let me know if you need any more help! 👍

**Comment by ZachJW34** [comment]
[10.3.0](https://github.com/nrwl/nx/commit/31304d4d01bb6f0e5a04082ec72e64c78a0e6756) has been released with a [new eslint builder](https://github.com/nrwl/nx/commit/e22f9370f57fc524851b22de55650f1d6e280599). We might be able to take advantage of this!

**Comment by BuckyMaler** [comment]
I'll look into this soon. 🤞

**Comment by BuckyMaler** [comment]
Updating to Nx v10.3.0 fixes this issue. I'll get to work on the update.
